spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-client

server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/

